-- Could not auto-generate a down migration
-- Please write an appropriate down migration for the SQL below:
-- ALTER TABLE public.league_seasons ADD google_sheet_id text NOT NULL;
-- ALTER TABLE public.league_seasons ADD google_sheet_name text NOT NULL;
-- ALTER TABLE public.league_seasons ADD google_sheet_range_start text NOT NULL;
