-- Could not auto-generate a down migration
-- Please write an appropriate down migration for the SQL below:
-- ALTER TABLE public.admin_key_value ADD CONSTRAINT admin_key_value_name_unique UNIQUE (name);
