name: Pull request bump version

on:
  pull_request:
    branches: ["main"]

jobs:
  version-bump:
    name: "Bump version"
    runs-on: ubuntu-latest
    steps:
      - name : Bump version
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: ./scripts/bump-version.sh $TITLE
