# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Pull request

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: "Build & Test"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          ssh-key: ${{ secrets.DEPLOY_KEY }} # Private ssh key
      - name: Debug SSH Authentication
        run: |
          ssh -vT git@github.com || true
          ssh-add -L || echo "No keys loaded"
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm run create-config
      - run: npm run build
      - run: npm run test
